title: Hello!
copyright:   1996-2021
version:     (V002-04-Jan-2021)
description: (V002-04-Jan-2021) 
      Hello!  This site is managed by VauLSMorg (vlsm.org) since 2021.
google_analytics: UA-89852122-6
disc: XXX.
      XXX.
author: Cicak Bin Kadal
show_downloads: false
theme: jekyll-theme-hacker
sitemap: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
social:
  name: URLs
  links:
    - https://https://github.com/rms46/jekyllTester

# github:
#    zip_url: https://github.com/...
#    tar_url: https://github.com/...

github: [metadata]

