title: The VauLSMorg (vlsm.org) Archive
copyright:    1996-2021
version:       118---15-Jan-2021
description: (V118---15-Jan-2021) 
      This site is managed by VauLSMorg (vlsm.org) since 1996.
google_analytics: UA-89852122-4
disc: XXX.
      XXX.
author: Cicak Bin Kadal
show_downloads: false
theme: jekyll-theme-hacker
sitemap: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
social:
  name: URLs
  links:
    - https://https://github.com/rms46/jekyllTester

# github:
#    zip_url: https://github.com/...
#    tar_url: https://github.com/...

github: [metadata]

